footprint: [[0.10, -0.35], [0.10, 0.35], [-0.80, 0.35], [-0.80, -0.35]]
footprint_padding: 0.01
# robot_radius: 0.5

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.1

obstacle_range: 7.5
raytrace_range: 8.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser point_cloud
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}
    point_cloud: {sensor_frame: velodyne, data_type: PointCloud2, clearing: true, marking: true, topic: velodyne_points, inf_is_valid: true}

obstacles_lanes:
    observation_sources: lanes
    lanes: {data_type: LaserScan, clearing: true, marking: true, topic: lanes, inf_is_valid: true}


inflation:
    inflation_radius: 1
